spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/sample?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    url: jdbc:log4jdbc:mysql://localhost:3306/sample?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 240000


mybatis:
  type-aliases-package: com.example.mybatis.*
  mapper-locations: classpath:sqlmap/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

