spring:
  batch.job.enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/hjesmn?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 240000